/**
 * Species present in `@smogon/calc`'s bundled data that aren't real,
 * in-game-obtainable Pokémon — CAP (Create-A-Pokémon community fan
 * project) mons, plus a couple of calc-internal helper entries that
 * don't correspond to a selectable forme. None of these belong in a
 * VGC/Pokemon Champions team picker.
 *
 * `@smogon/calc` doesn't expose a "nonstandard"/CAP flag on its Specie
 * objects (it only ships types/baseStats/weight/abilities, trimmed down
 * from Showdown's full dex), so this list can't be derived at runtime.
 * It was generated by diffing the gen 9 species list against PokeAPI's
 * canonical `pokemon-species` list (base name, following `baseSpecies`
 * up to its root), which reliably isolates CAP mons since they aren't
 * built on top of any real species. Two real formes came up as false
 * positives from that diff — Aegislash-Blade and Aegislash-Shield are
 * genuine, commonly-used competitive formes; PokeAPI just doesn't have
 * a suffix-less "Aegislash" species entry to match against — and were
 * manually excluded from this list. `Aegislash-Both` *is* excluded: it's
 * a calc-internal combined entry, not a forme a player can select.
 *
 * If `@smogon/calc`'s data is ever updated with new CAP mons, this list
 * will need regenerating the same way.
 */
export const NONSTANDARD_SPECIES = new Set([
	'Ababo',
	'Aegislash-Both',
	'Argalis',
	'Arghonaut',
	'Astrolotl',
	'Aurumoth',
	'Brattler',
	'Breezi',
	'Caimanoe',
	'Caribolt',
	'Cawdet',
	'Cawmodore',
	'Chromera',
	'Chuggalong',
	'Chuggon',
	'Colossoil',
	'Coribalis',
	'Cresceidon',
	'Crucibelle',
	'Crucibelle-Mega',
	'Cupra',
	'Cyclohm',
	'Dorsoil',
	'Draggalong',
	'Duohm',
	'Electrelk',
	'Embirch',
	'Equilibra',
	'Fawnifer',
	'Fidgit',
	'Flarelm',
	'Floatoy',
	'Hemogoblin',
	'Jumbao',
	'Justyke',
	'Kerfluffle',
	'Kitsunoh',
	'Krilowatt',
	'Malaconda',
	'Miasmaw',
	'Miasmite',
	'Mollux',
	'Monohm',
	'Mumbao',
	'Naviathan',
	'Necturine',
	'Necturna',
	'Nohface',
	'Pajantom',
	'Plasmanta',
	'Pluffle',
	'Privatyke',
	'Protowatt',
	'Pyroak',
	'Ramnarok',
	'Ramnarok-Radiant',
	'Rebble',
	'Revenankh',
	'Saharaja',
	'Saharascal',
	'Scattervein',
	'Scratchet',
	'Shox',
	'Smogecko',
	'Smoguana',
	'Smokomodo',
	'Snaelstrom',
	'Snugglow',
	'Solotl',
	'Stratagem',
	'Swirlpool',
	'Syclant',
	'Syclar',
	'Tactite',
	'Tomohawk',
	'Venomicon',
	'Venomicon-Epilogue',
	'Volkraken',
	'Volkritter',
	'Voodoll',
	'Voodoom'
]);
